import unittest #unittest provides a framework for testing.

from T2D_Risk_Ver_6_25_25 import calculate_risk #In the terminal, the code python -m unittest test_T2D_Risk_Ver_6_25_25 must be written in the terminal to run the test.

class TestRisk(unittest.TestCase):

    def test_all_false(self): #This is the first test of the program, to receive a value of 0 from calculate_risk() in the T2D_Risk_Ver_6_25_25 program.
        self.assertEqual(calculate_risk(False, False, False, False, False, False, 0, False, False, False, False, False, False, False,  0), "low") #The purpose of .assertEqual is to check if the value generated by calculate_risk(), with its given values, is equal to the second value.


if __name__ == '__main__':
    unittest.main() #Calls the main function of T2D_Risk_Ver_6_25_25.
